sys-apps/systemd boot cryptsetup ukify
gnome-base/gdm -X
gnome-base/nautilus -previewer
media-video/pipewire bluetooth extra libcamera pipewire-alsa sound-server
net-misc/networkmanager -ppp -wext
x11-drivers/nvidia-drivers kernel-open modules-compress modules-sign -tools
app-admin/conky bundled-toluapp iostats lua-rsvg truetype
sys-apps/kmod pkcs7
sys-kernel/linux-firmware compress-zstd
sys-auth/polkit -gtk
gnome-extra/gnome-software -firmware
app-crypt/pinentry -gtk
media-plugins/gst-plugins-meta ffmpeg taglib
x11-wm/mutter -screencast
gnome-base/gnome -classic
net-libs/nodejs npm
media-libs/glycin-loaders gtk thumbnailer
sys-libs/zlib minizip
dev-lang/rust-bin rustfmt
media-libs/libcamera -sdl
gnome-base/gvfs google
sys-firmware/intel-microcode hostonly
sys-kernel/installkernel dracut systemd-boot uki ukify
sys-kernel/gentoo-kernel -debug
media-libs/gd fontconfig
